### ISSUE TITLE
bios location is different on fedora

### ISSUE THREAD

**Issue by fwilhe2** [afbjorklund/lima-the-hard-way#2]
It seems like in this command

```
qemu-system-x86_64 -accel kvm -smp 1 -m 1024 \
                   -hda disk.img -cdrom seed.img \
                   -net nic -net user,hostfwd=tcp::2222-:22 \
                   -bios /usr/share/qemu/OVMF.fd
```

the bios file path needs to be replaced with `/usr/share/OVMF/OVMF_CODE.fd` when running on fedora.

**Comment by afbjorklund** [comment]
Yeah, Lima has a long list of various search paths for it...
It is also different on aarch64, not using OVMF (but AAVMF)

But I think you need to merge code and vars too, using UEFI is much more complicated than BIOS was

The QEMU installation (deb) tried to fix the firmware location with JSON, so now we have _two_ problems

`/usr/share/qemu/firmware/60-edk2-x86_64.json`

`/usr/share/qemu/firmware/60-edk2-aarch64.json`

**Comment by afbjorklund** [comment]
"Nothing complicated" about this wall of text, how to build a OVMF.fd

https://github.com/tianocore/tianocore.github.io/wiki/How-to-run-OVMF

And that is even _without_ Secure Boot.

Then it gets **worse**. Sheesh.

**Comment by afbjorklund** [comment]
Left as an exercise for the reader, Fedora people should be used to tweaking?

`uefi=/usr/share/qemu/OVMF.fd`

Even the JSON file is in a different location. And `virt-install` does the [assembly](https://docs.fedoraproject.org/en-US/quick-docs/uefi-with-qemu/).

/usr/share/qemu/firmware/50-edk2-ovmf-4m-qcow2-x64-nosb.json

**Comment by afbjorklund** [comment]
Using the basic path now, in 35a2df19c7085d97bcf8e0f1bbec59da059b314d
